#!/usr/bin/env bash
# Bash script that will display information about subdomains

aux_function () {
    input=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $input" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  aux_function "$1" "www"
  aux_function "$1" "lb-01"
  aux_function "$1" "web-01"
  aux_function "$1" "web-02"
elif [ "$#" == 2 ]
then
  aux_function "$1" "$2"
fi
