#!/usr/bin/env bash
# Install nginx on your web-01 server
# In the HTML file, delete everything inside body
# and write Hello World! inside it

sudo apt update
sudo apt-get -y install nginx
cd /var/www/html
sudo chmod 777 index.nginx-debian.html
echo Hello World! > index.nginx-debian.html
sudo service nginx restart
