#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt-get install -y haproxy
echo "listen 4438-lb-01 " | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4438-web-01 52.7.138.71:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4438-web-02 54.234.82.120:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
