#!/usr/bin/env bash
# script with the minimum number of commands to automate your fix
#
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
