#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
